// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://samoubhkkdpzelqzsyei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhbW91Ymhra2RwemVscXpzeWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3Mjk1MzQsImV4cCI6MjA3MjMwNTUzNH0.iN9VH5GzU6CqiFLj6kxxsa6u0eJAvSOHoUITKF7MRo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});